[package]
name = "itoken-inference"
version = "0.1.0"
edition = "2021"

[dependencies]
itoken-core = { path = "../itoken-core" }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true }
tracing = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
async-stream = "0.3"
